version: '3'
services:
  java-seminar-timetable:
    image: solr:8.7
    user: "1000:1000"
    ports:
      - "8983:8983"
    volumes:
      - ~/docker-volumes/solr-data-timetable:/var/solr
    command:
      - solr-precreate
      - timetable
    networks:
      - backend

  java-seminar-users:
    image: solr:8.7
    user: "1000:1000"
    ports:
      - "8984:8983"
    volumes:
      - ~/docker-volumes/solr-data-users:/var/solr
    command:
      - solr-precreate
      - users
    networks:
      - backend

networks:
  backend:
    external: true